---

- hosts: all
  become: true
  tasks:

          #Update Repo        
  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


        #Install apache2
  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"
