---

- name: service status
  hosts: all
  tasks:
  - name: service status
    command: systemctl status "{{ item }}"
    with_items:
                    -sshd.service
                    -ufw.service
    when: ansible_distribution == "Ubuntu"
    register: result
    ignore_errors: yes
  - name: service status
    debug:
     var: result
             

           
          
